# fly.toml app configuration file generated for thereyougo on 2023-10-12T08:25:27+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "thereyougo"
primary_region = "cdg"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.2"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"
  MYSQL_ATTR_SSL_CA = "/etc/ssl/certs/ca-certificates.crt"
  DB_CONNECTION = "mysql"
  DB_PORT = 3306
  APP_NAME = "There You Go"
  APP_DEBUG=false
  APP_URL = "https://thereyougo.eu"
  VITE_USER_NODE_ENV="production"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[mounts]
  source="images_vol"
  destination="/var/www/html/storage"

[processes]
  app = ""
  workers = "php artisan queue:listen"